CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    age INTEGER,
    email VARCHAR(255),
    last_name VARCHAR(255),
    name VARCHAR(255),
    password VARCHAR(255),
    PRIMARY KEY (id)
);